# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      link:
        description: 'ROMLINK'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          wget "${{ github.event.inputs.link }}" -O Xiaomi_HyperOS.zip
          unzip -d Xiaomi_HyperOS Xiaomi_HyperOS.zip
          sudo apt update
          sudo apt install zstd
          cd Xiaomi_HyperOS
          zstd  --rm -d super.zst -o super.img
          mv super.img ${{ github.workspace }}/TIK4/Xiaomi_HyperOS
      - name: Run a multi-line script
        run: |
          ./run
            1
              2
                11
                  00
                    4
                      1
                        0

